# see https://github.com/stelligent/xaap/actions after each git-push
name: Deploy

on: [push]

env:
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1
  CLOUDSDK_CORE_PROJECT: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
  CLOUDSDK_COMPUTE_REGION: ${{ secrets.CLOUDSDK_COMPUTE_REGION }}
  CLOUDSDK_COMPUTE_ZONE: ${{ secrets.CLOUDSDK_COMPUTE_ZONE }}
  CLOUDSDK_RUN_REGION: ${{ secrets.CLOUDSDK_COMPUTE_REGION }}
  CLOUDSDK_SERVICE_ACCOUNT: ${{ secrets.CLOUDSDK_SERVICE_ACCOUNT }}
  GOOGLE_APPLICATION_CREDENTIALS: gcp-slack-notifier.key

jobs:
  check:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - id: env
        name: Environment prep
        run: make gcloud-auth printenv
        env:
            PIPENV_DEV: "true"

      - id: test
        name: Test our code before deploying
        run: make python-reqs code-test
        env:
            PIPENV_DEV: "true"

  deploy:
    name: Deploy Google Cloud Function
    #runs-on: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@master

      - id: env
        name: Environment prep
        run: "id && env |sort && env |egrep '^(CLOUDSDK|GOOGLE)'"

      - id: gcloud-prep
        name: Grab Google Cloud service account key
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' >${{ env.GOOGLE_APPLICATION_CREDENTIALS }}

      - id: gcloud-download
        name: Download Google Cloud SDK
        run: curl -o gcloud.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-297.0.1-linux-x86_64.tar.gz && tar xf gcloud.tar.gz && rm gcloud.tar.gz

      - id: gcloud-path
        name: Configure job PATH to use Google Cloud SDK
        run: export PATH=$PATH:${{ env.HOME }}/google-cloud-sdk/bin

      #- id: enable-gcp-apis
      #  name: Enable APIs necessary for deployment
      #  run: make gcloud-apis

      - id: python-dependencies
        name: Install python dependencies
        run: make python-reqs

      - id: gcloud-auth
        name: Authenticate to Google Cloud Platform
        run: make gcloud-auth

      - id: deploy-function
        name: Deploy the budget alerts code as a Google Cloud Function
        run: make deploy
